import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import * as icons from 'bootstrap-icons/font/bootstrap-icons.css';
import { createPopper } from '@popperjs/core';
import "./globals.css";
import BootstrapClient from '@/app/components/client_config/bootstrapClient';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shark Afiliados",
  description: "Generated by create Fabuloso",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="pt-br">
        <body>
          <BootstrapClient />
          {children}
        </body>
      </html>
    </>
  );
}