import "./global.css";
import VerificationSession from "../components/redirect/sessionRedirect";
import MainContainer from "../components/menu_user/MainCointainer";
import * as icons from 'bootstrap-icons/font/bootstrap-icons.css';

import { getServerSession } from "next-auth";
import { redirect } from 'next/navigation';

export const metadata = {
  title: "Shark Afiliados",
  description: "Generated by create Fabuloso",
};

export default async function UserLayout({ children }) {
  const session = await getServerSession();

  if(!session){
    redirect("/login/signin");
  }

  return (
    <>
      <html lang="pt-br">
        <body>
          <MainContainer>
            {children}
          </MainContainer>
        </body>
      </html>
    </>
  );
}